# Exercícios NumPy  

#### Importe NumPy como np

In [1]:
import numpy as np

#### Crie uma matriz de zeros

#### Crie uma matriz de ones

#### Crie um array de inteiros de 1 até 100

#### Crie um array dos numeros pares de 2 até 100

#### Criei uma matriz 4x4 com valores variando de 0 até 15

#### Crie uma matriz identidade 3x3

#### Crie uma matriz de números inteiros

#### Crie um array de tamanho 10 igualmente espaçado entre 0 e 20.

## Indexação e Seleção

Dada a matriz:

In [2]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Reproduza as saídas das linhas abaixo.

Cuidado ao tentar reproduzir os resultados na mesma linha pois a execução substituirá o resultado previsto.

array([1, 2, 3, 4])

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[10, 11, 12],
       [14, 15, 16]])

array([[11, 12],
       [15, 16]])

array([[11]])

### Utilizando a mesma matriz dos exercícios acima, obtenha os valores abaixo:

#### Máximo

#### Desvio padrão

### Desafios

#### Some todos os valores

#### Obtenha a soma por coluna