# Exercícios NumPy  

#### Importe NumPy como np

In [135]:
import numpy as np

#### Crie uma matriz de zeros

In [136]:
m_zeros = np.zeros([3,3])
m_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### Crie uma matriz de ones

In [159]:
m_ones = np.ones([3,3])
m_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Crie um array de inteiros de 1 até 100

In [138]:
v_1ate100 = np.arange(1, 101)
v_1ate100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### Crie um array dos numeros pares de 2 até 100

In [139]:
v_pares = np.arange(2, 101, 2)
v_pares

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

#### Criei uma matriz 4x4 com valores variando de 0 até 15

In [140]:
m_4por4 = np.random.randint(0, 16, [4,4])
m_4por4

array([[ 5,  6,  3,  3],
       [ 1,  5,  5,  8],
       [ 5,  0, 12,  0],
       [13,  9, 11, 10]])

#### Crie uma matriz identidade 3x3

In [141]:
m_id = np.eye(3,3)
m_id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Crie uma matriz de números inteiros

In [142]:
m_inteiros = np.random.randint(-100, 100, [3,3])
m_inteiros

array([[-16,  21,  91],
       [-67,  34,   9],
       [-33, -66,  89]])

#### Crie um array de tamanho 10 igualmente espaçado entre 0 e 20.

In [143]:
v_espacado = np.linspace(0, 20, 10)
v_espacado

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## Indexação e Seleção

Dada a matriz:

In [144]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Reproduza as saídas das linhas abaixo.

Cuidado ao tentar reproduzir os resultados na mesma linha pois a execução substituirá o resultado previsto.

In [155]:
arr[0]

array([1, 2, 3, 4])

In [157]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [147]:
arr[2:4,1:4]

array([[10, 11, 12],
       [14, 15, 16]])

In [148]:
arr[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [158]:
arr[2,2:3]

array([11])

### Utilizando a mesma matriz dos exercícios acima, obtenha os valores abaixo:

#### Máximo

In [150]:
np.max(arr)

16

#### Desvio padrão

In [151]:
arr.std()

4.6097722286464435

### Desafios

#### Some todos os valores

In [152]:
np.sum(arr)

136

#### Obtenha a soma por coluna

In [153]:
print('Primeira coluna:', np.sum(arr[0:4, 0]))
print('Segunda coluna:', np.sum(arr[0:4, 1]))
print('Terceira coluna:', np.sum(arr[0:4, 2]))
print('Quarta coluna:', np.sum(arr[0:4, 3]))


Primeira coluna: 28
Segunda coluna: 32
Terceira coluna: 36
Quarta coluna: 40
